sudo: false

language: java

matrix:
  include:
  - jdk: oraclejdk7
    env: TERM=dumb MOCK_MAKER=mock-maker-inline KOTLIN_VERSION=1.0.5
  - jdk: oraclejdk7
    env: TERM=dumb MOCK_MAKER=mock-maker-inline KOTLIN_VERSION=1.1-M02
  - jdk: oraclejdk8
    env: TERM=dumb MOCK_MAKER=mock-maker-inline KOTLIN_VERSION=1.0.5
  - jdk: oraclejdk8
    env: TERM=dumb MOCK_MAKER=mock-maker-inline KOTLIN_VERSION=1.1-M02


env:
  matrix:
  - TERM=dumb

install:
 - true

script:
  - ./gradlew test

notifications:
  email: false